# -*- coding: utf-8 -*-
"""Red CNN op.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LlmE6MOw6OPBLYbZkAoIV97asx7WEuML
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import os
import re
import matplotlib.pyplot as plt
# %matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

import keras
from keras.utils import to_categorical
from keras.models import Sequential,Input,Model
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.layers.normalization import BatchNormalization
from keras.layers.advanced_activations import LeakyReLU

from google.colab import files
##El zip debe estar subido a content de colab
uploaded = files.upload()

import zipfile
zip_ref = zipfile.ZipFile("dataset-resized.zip", 'r')
zip_ref.extractall()
zip_ref.close()

import matplotlib.pyplot as plt

from skimage import data, color
from skimage.transform import resize
def imagerescaled(image):
  image_resized = resize(image, (image.shape[0] / 4, image.shape[1] / 4),
                         anti_aliasing=True)
  return image_resized

dirname = os.path.join(os.getcwd(), 'dataset-resized')
imgpath = dirname + os.sep 

images = []
directories = []
dircount = []
prevRoot=''
cant=0

print("leyendo imagenes de ",imgpath)

for root, dirnames, filenames in os.walk(imgpath):
    for filename in filenames:
        if re.search("\.(jpg|jpeg|png|bmp|tiff)$", filename):
            if prevRoot !=root:
                print(root, cant)
                prevRoot=root
                directories.append(root)
                dircount.append(cant)
                cant=0
            filepath = os.path.join(root, filename)
            image = plt.imread(filepath)
            images.extend(augmentedImg(imagerescaled(image)))
            cant=cant+3
            b = "Leyendo..." + str(cant)
            print (b, end="\r")
dircount.append(cant)
dircount = dircount[1:]
#dircount[0]=dircount[0]+1
print('Directorios leidos:',len(directories))
print("Imagenes en cada directorio", dircount)
print('suma Total de imagenes en subdirs:',sum(dircount))

labels=[]
indice=0
for cantidad in dircount:
    for i in range(cantidad):
        labels.append(indice)
    indice=indice+1
print("Cantidad etiquetas creadas: ",len(labels))

materiales=[]
indice=0
for directorio in directories:
    name = directorio.split(os.sep)
    print(indice , name[len(name)-1])
    materiales.append(name[len(name)-1])
    indice=indice+1

y = np.array(labels)
X = np.array(images) #convierto de lista a numpy

# Find the unique numbers from the train labels
classes = np.unique(y)
nClasses = len(classes)
print('Total number of outputs : ', nClasses)
print('Output classes : ', classes)

#hacer split por clase no por total

train_X,test_X,train_Y,test_Y = train_test_split(X,y,test_size=0.3)
print('Training data shape : ', train_X.shape, train_Y.shape)
print('Testing data shape : ', test_X.shape, test_Y.shape)

plt.figure(figsize=[5,5])

# Display the first image in training data
plt.subplot(121)
plt.imshow(train_X[0], cmap='gray')
plt.title("Ground Truth : {}".format(train_Y[0]))

# Display the first image in testing data
plt.subplot(122)
plt.imshow(test_X[0], cmap='gray')
plt.title("Ground Truth : {}".format(test_Y[0]))

#train_X = np.reshape(train_X,(2021,96,128,1))
#test_X = np.reshape(test_X,(506,96,128,1))

train_X = train_X.astype('float32')
test_X = test_X.astype('float32')
train_X = train_X / 255.
test_X = test_X / 255.

# Change the labels from categorical to one-hot encoding
train_Y_one_hot = to_categorical(train_Y)
test_Y_one_hot = to_categorical(test_Y)

# Display the change for category label using one-hot encoding
print('Original label:', train_Y[0])
print('After conversion to one-hot:', train_Y_one_hot[0])

#Mezclar todo y crear los grupos de entrenamiento y testing
train_X,valid_X,train_label,valid_label = train_test_split(train_X, train_Y_one_hot, test_size=0.2, random_state=13)

print(train_X.shape,valid_X.shape,train_label.shape,valid_label.shape)

#declaramos variables con los parámetros de configuración de la red
INIT_LR = 1e-3 # Valor inicial de learning rate. El valor 1e-3 corresponde con 0.001
epochs = 100 # Cantidad de iteraciones completas al conjunto de imagenes de entrenamiento
batch_size = 32 # cantidad de imágenes que se toman a la vez en memoria

material_model = Sequential()
material_model.add(Conv2D(32, kernel_size=(3, 3),activation='linear',padding='same',input_shape=(96,128,3)))
material_model.add(LeakyReLU(alpha=0.1))
material_model.add(MaxPooling2D((2, 2),padding='same'))
material_model.add(Dropout(0.5))

material_model.add(Flatten())
material_model.add(Dense(32, activation='linear'))
material_model.add(LeakyReLU(alpha=0.1))
material_model.add(Dropout(0.5))
material_model.add(Dense(nClasses, activation='softmax'))

material_model.summary()

material_model.compile(loss=keras.losses.categorical_crossentropy, optimizer=keras.optimizers.Adagrad(lr=INIT_LR, decay=INIT_LR / 100),metrics=['accuracy'])

material_train = material_model.fit(train_X, train_label, batch_size=batch_size,epochs=epochs,verbose=1,validation_data=(valid_X, valid_label))

# guardamos la red, para reutilizarla en el futuro, sin tener que volver a entrenar
material_model.save("material_mnist.h5py")

test_eval = material_model.evaluate(test_X, test_Y_one_hot, verbose=1)

print('Test loss:', test_eval[0])
print('Test accuracy:', test_eval[1])

accuracy = material_train.history['acc']
val_accuracy = material_train.history['val_acc']
loss = material_train.history['loss']
val_loss = material_train.history['val_loss']
epochs = range(len(accuracy))
plt.plot(epochs, accuracy, 'bo', label='Training accuracy')
plt.plot(epochs, val_accuracy, 'b', label='Validation accuracy')
plt.title('Training and validation accuracy')
plt.legend()
plt.figure()
plt.plot(epochs, loss, 'bo', label='Training loss')
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.legend()
plt.show()



predicted_classes2 = material_model.predict(test_X)

predicted_classes=[]
for predicted_material in predicted_classes2:
    predicted_classes.append(predicted_material.tolist().index(max(predicted_material)))
predicted_classes=np.array(predicted_classes)

predicted_classes.shape, test_Y.shape

#Qué mejorar
correct = np.where(predicted_classes==test_Y)[0]
print("Found %d correct labels" % len(correct))
for i, correct in enumerate(correct[0:9]):
    plt.subplot(3,3,i+1)
    plt.imshow(test_X[correct].reshape(96,128,3), cmap='gray')
    plt.title("{}, {}".format(materiales[predicted_classes[correct]],
                                                    materiales[test_Y[correct]]))

    plt.tight_layout()

incorrect = np.where(predicted_classes!=test_Y)[0]
print("Found %d incorrect labels" % len(incorrect))
for i, incorrect in enumerate(incorrect[0:9]):
    plt.subplot(3,3,i+1)
    plt.imshow(test_X[incorrect].reshape(96,128,3), cmap='gray', interpolation='none')
    plt.title("{}, {}".format(materiales[predicted_classes[incorrect]],
                                                    materiales[test_Y[incorrect]]))
    plt.tight_layout()

target_names = ["Class {}".format(i) for i in range(nClasses)]
print(classification_report(test_Y, predicted_classes, target_names=target_names))